### ISSUE TITLE
plugin doesn't work in IntelliJ 10.5.1

### ISSUE THREAD

**Issue by adamjmurray** [yeungda/coffeescript-idea#11]
I am unable to type text into a coffeescript file. Upon opening a .coffee file. I get the exception below. 

I just tried the plugin for the first time, so I have no idea how long this has been a problem. I don't think this matters, but I installed the plugin manually because of this issue: https://github.com/yeungda/coffeescript-idea/issues/8

java.lang.NoClassDefFoundError: com/intellij/psi/impl/source/tree/PlainTextFileElement
    at coffeescript.lang.ParserDefinition$1.parse(Unknown Source)
    at com.intellij.psi.tree.IFileElementType.parseContents(IFileElementType.java:41)
    at com.intellij.psi.impl.source.tree.LazyParseableElement.b(LazyParseableElement.java:177)
    at com.intellij.psi.impl.source.tree.LazyParseableElement.getFirstChildNode(LazyParseableElement.java:218)
    at com.intellij.psi.impl.source.tree.LazyParseableElement.getFirstChildNode(LazyParseableElement.java:32)
    at com.intellij.psi.impl.source.tree.SharedImplUtil.getFirstChild(SharedImplUtil.java:47)
    at com.intellij.psi.impl.source.PsiFileImpl.getFirstChild(PsiFileImpl.java:704)
    at com.intellij.psi.SingleRootFileViewProvider.findElementAt(SingleRootFileViewProvider.java:388)
    at com.intellij.psi.SingleRootFileViewProvider.findElementAt(SingleRootFileViewProvider.java:375)
    at com.intellij.psi.impl.source.PsiFileImpl.findElementAt(PsiFileImpl.java:516)
    at com.intellij.ide.browsers.actions.BaseWebBrowserAction.getElement(BaseWebBrowserAction.java:107)
    at com.intellij.ide.browsers.actions.BaseWebBrowserAction.update(BaseWebBrowserAction.java:74)
    at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareUpdate(ActionUtil.java:98)
    at com.intellij.openapi.actionSystem.impl.Utils.a(Utils.java:162)
    at com.intellij.openapi.actionSystem.impl.Utils.expandActionGroup(Utils.java:124)
    at com.intellij.openapi.actionSystem.impl.Utils.expandActionGroup(Utils.java:84)
    at com.intellij.openapi.actionSystem.impl.Utils.expandActionGroup(Utils.java:141)
    at com.intellij.openapi.actionSystem.impl.ActionToolbarImpl$2.run(ActionToolbarImpl.java:755)
    at com.intellij.openapi.wm.impl.FocusManagerImpl.a(FocusManagerImpl.java:509)
    at com.intellij.openapi.wm.impl.FocusManagerImpl.e(FocusManagerImpl.java:492)
    at com.intellij.openapi.wm.impl.FocusManagerImpl.d(FocusManagerImpl.java:476)
    at com.intellij.openapi.wm.impl.FocusManagerImpl.access$200(FocusManagerImpl.java:52)
    at com.intellij.openapi.wm.impl.FocusManagerImpl$7.run(FocusManagerImpl.java:407)
    at com.intellij.util.ui.UIUtil.invokeLaterIfNeeded(UIUtil.java:1432)
    at com.intellij.openapi.wm.impl.FocusManagerImpl.doWhenFocusSettlesDown(FocusManagerImpl.java:390)
    at com.intellij.openapi.actionSystem.impl.ActionToolbarImpl.a(ActionToolbarImpl.java:801)
    at com.intellij.openapi.actionSystem.impl.ActionToolbarImpl.access$400(ActionToolbarImpl.java:58)
    at com.intellij.openapi.actionSystem.impl.ActionToolbarImpl$MyTimerListener.run(ActionToolbarImpl.java:713)
    at com.intellij.openapi.actionSystem.impl.WeakTimerListener.run(WeakTimerListener.java:50)
    at com.intellij.openapi.actionSystem.impl.ActionManagerImpl$MyTimer.a(ActionManagerImpl.java:1250)
    at com.intellij.openapi.actionSystem.impl.ActionManagerImpl$MyTimer.a(ActionManagerImpl.java:1239)
    at com.intellij.openapi.actionSystem.impl.ActionManagerImpl$MyTimer.actionPerformed(ActionManagerImpl.java:1220)
    at javax.swing.Timer.fireActionPerformed(Timer.java:291)
    at javax.swing.Timer$DoPostEvent.run(Timer.java:221)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:209)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:677)
    at java.awt.EventQueue.access$000(EventQueue.java:85)
    at java.awt.EventQueue$1.run(EventQueue.java:638)
    at java.awt.EventQueue$1.run(EventQueue.java:636)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:87)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:647)
    at com.intellij.ide.IdeEventQueue.e(IdeEventQueue.java:662)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:515)
    at com.intellij.ide.IdeEventQueue.b(IdeEventQueue.java:411)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:369)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:296)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:211)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:196)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:188)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:122)
Caused by: java.lang.ClassNotFoundException: com.intellij.psi.impl.source.tree.PlainTextFileElement
    at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:70)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
    ... 52 more

**Comment by Ankoul** [comment]
same here with AndroidStudio 1.2.2

**Comment by adamjmurray** [comment]
This project is abandoned. I'm cleaning up my created issues list.
